version: '3.8'
services:
  mongoimport:
    image: library/mongo:latest
    container_name: my-import
    volumes:
      - ./timetable.json:/src/data/timetable.json
      - ./user.json:/src/data/user.json
    command: sh -c "mongoimport --host mongodb -d UoPS
      -c timetable --drop --file /src/data/timetable.json --jsonArray &&
      mongoimport --host mongodb -d UoPS -c users --drop
      --file /src/data/user.json --jsonArray"
  mongodb:
    image: library/mongo:latest
    ports:
      - 27017:27017
    depends_on:
      - mongoimport
    restart: always
    volumes:
      - data:/data/db
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
